# fly.toml app configuration file generated for fullstackopen-part13-thrumming-mountain-8183 on 2024-11-15T09:54:09+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fullstackopen-part13-thrumming-mountain-8183'
primary_region = 'otp'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
